### REFRESH TOKEN
GET http://localhost:5000/token
Cookie: refreshToken=PASTE_YOUR_REFRESH_TOKEN_HERE

###

### LOGOUT
DELETE http://localhost:5000/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

###

### REGISTER USER BARU
POST http://localhost:5000/register
Content-Type: application/json

{
  "name": "Adwin",
  "email": "admin@gmail.com",
  "password": "admin123",
  "role": "admin"
}

###

### LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "petugas1@example.com",
  "password": "123456"
}

###

### GET SEMUA USER (Protected)
GET http://localhost:5000/users
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### GET USER BY ID
GET http://localhost:5000/users/1
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### UPDATE USER
PUT http://localhost:5000/update-user/1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
  "name": "Petugas Satu",
  "email": "petugas1@example.com",
  "password": "123456"
}

###

### DELETE USER
DELETE http://localhost:5000/delete-user/1
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### GET SEMUA KEGIATAN KERJA
GET http://localhost:5000/kegiatan-kerja
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### GET KEGIATAN KERJA BY ID
GET http://localhost:5000/kegiatan-kerja/1
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### ADD KEGIATAN KERJA
POST http://localhost:5000/add-kegiatan-kerja
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
  "nama_kegiatan": "Pelatihan Digital",
  "deskripsi": "BUTUH BANYAK UANGG",
  "tanggal": "2025-06-01",
  "userId": 1
}

###

### UPDATE KEGIATAN KERJA
PUT http://localhost:5000/update-kegiatan-kerja/1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
  "nama_kegiatan": "Pelatihan",
  "tanggal": "2025-06-02"
}

###

### DELETE KEGIATAN KERJA
DELETE http://localhost:5000/delete-kegiatan-kerja/3
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### GET SEMUA ANGGARAN
GET http://localhost:5000/anggaran
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### GET ANGGARAN BY ID
GET http://localhost:5000/anggaran/3
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

###

### ADD ANGGARAN
POST http://localhost:5000/add-anggaran
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
  "keterangan": "Kardus",
  "jumlah": 5,
  "harga": 15000,
  "kegiatanKerjaId": 3
}

###

### UPDATE ANGGARAN
PUT http://localhost:5000/update-anggaran/1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE

{
  "keterangan": "Kardus Besar",
  "jumlah": 10,
  "harga": 20000
}

###
